export type Category = {
  id: number;
  parent_id: number | null;
  name: string;
};

export const categories: Category[] = [
  { id: 1, parent_id: null, name: "전자기기" },
  { id: 2, parent_id: 1, name: "모바일/태블릿" },
  { id: 3, parent_id: 2, name: "스마트폰" },
  { id: 4, parent_id: 2, name: "태블릿" },
  { id: 5, parent_id: 2, name: "웨어러블 기기" },
  { id: 6, parent_id: 2, name: "액세서리" },
  { id: 7, parent_id: 1, name: "컴퓨터/노트북" },
  { id: 8, parent_id: 7, name: "데스크탑" },
  { id: 9, parent_id: 7, name: "노트북" },
  { id: 10, parent_id: 7, name: "모니터" },
  { id: 11, parent_id: 7, name: "주변기기" },
  { id: 12, parent_id: 7, name: "부품" },
  { id: 13, parent_id: 1, name: "가전제품" },
  { id: 14, parent_id: 13, name: "TV/오디오" },
  { id: 15, parent_id: 13, name: "주방가전" },
  { id: 16, parent_id: 13, name: "생활가전" },
  { id: 17, parent_id: 13, name: "계절가전" },
  { id: 18, parent_id: null, name: "패션/의류" },
  { id: 19, parent_id: 18, name: "여성의류" },
  { id: 20, parent_id: 19, name: "상의" },
  { id: 21, parent_id: 19, name: "하의" },
  { id: 22, parent_id: 19, name: "원피스/세트" },
  { id: 23, parent_id: 19, name: "아우터" },
  { id: 24, parent_id: 19, name: "언더웨어" },
  { id: 25, parent_id: 18, name: "남성의류" },
  { id: 26, parent_id: 25, name: "상의" },
  { id: 27, parent_id: 25, name: "하의" },
  { id: 28, parent_id: 25, name: "정장/세트" },
  { id: 29, parent_id: 25, name: "아우터" },
  { id: 30, parent_id: 25, name: "언더웨어" },
  { id: 31, parent_id: 18, name: "신발가방" },
  { id: 32, parent_id: 31, name: "여성신발" },
  { id: 33, parent_id: 31, name: "남성신발" },
  { id: 34, parent_id: 31, name: "가방/지갑" },
  { id: 35, parent_id: 31, name: "여행용품" },
  { id: 36, parent_id: 18, name: "액세서리주얼리" },
  { id: 37, parent_id: 36, name: "시계" },
  { id: 38, parent_id: 36, name: "주얼리" },
  { id: 39, parent_id: 36, name: "모자/벨트" },
  { id: 40, parent_id: 36, name: "기타 액세서리" },
  { id: 41, parent_id: null, name: "가구/인테리어" },
  { id: 42, parent_id: 41, name: "가구" },
  { id: 43, parent_id: 42, name: "침실가구" },
  { id: 44, parent_id: 42, name: "거실가구" },
  { id: 45, parent_id: 42, name: "주방가구" },
  { id: 46, parent_id: 42, name: "사무용가구" },
  { id: 47, parent_id: 41, name: "인테리어" },
  { id: 48, parent_id: 47, name: "조명" },
  { id: 49, parent_id: 47, name: "커튼/카펫" },
  { id: 50, parent_id: 47, name: "소품/장식품" },
  { id: 51, parent_id: 47, name: "침구류" },
  { id: 52, parent_id: null, name: "취미/레저" },
  { id: 53, parent_id: 52, name: "스포츠레저" },
  { id: 54, parent_id: 53, name: "운동용품" },
  { id: 55, parent_id: 53, name: "캠핑용품" },
  { id: 56, parent_id: 53, name: "낚시용품" },
  { id: 57, parent_id: 53, name: "자전거/보드" },
  { id: 58, parent_id: 52, name: "취미수집" },
  { id: 59, parent_id: 58, name: "음반/DVD" },
  { id: 60, parent_id: 58, name: "책/도서" },
  { id: 61, parent_id: 58, name: "게임" },
  { id: 62, parent_id: 58, name: "피규어/모델" },
  { id: 63, parent_id: 58, name: "수집품" },
  { id: 64, parent_id: null, name: "유아/아동" },
  { id: 65, parent_id: 64, name: "유아용품" },
  { id: 66, parent_id: 65, name: "유모차/카시트" },
  { id: 67, parent_id: 65, name: "장난감/교구" },
  { id: 68, parent_id: 65, name: "유아의류" },
  { id: 69, parent_id: 65, name: "유아가구" },
  { id: 70, parent_id: 64, name: "아동용품" },
  { id: 71, parent_id: 70, name: "아동의류" },
  { id: 72, parent_id: 70, name: "학용품" },
  { id: 73, parent_id: 70, name: "도서/교재" },
  { id: 74, parent_id: 70, name: "장난감" },
  { id: 75, parent_id: null, name: "뷰티/미용" },
  { id: 76, parent_id: 75, name: "화장품/향수" },
  { id: 77, parent_id: 76, name: "스킨케어" },
  { id: 78, parent_id: 76, name: "메이크업" },
  { id: 79, parent_id: 76, name: "향수" },
  { id: 80, parent_id: 76, name: "헤어케어" },
  { id: 81, parent_id: 75, name: "미용기기용품" },
  { id: 82, parent_id: 81, name: "미용가전" },
  { id: 83, parent_id: 81, name: "네일/헤어 용품" },
];
